### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by peaceofmind3241** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#19]
I used your work for T430 Monterey 12.0.1. It is stable. Many thanks!
I tried to connect to an external Display through thunderbolt. somehow no connection. Also tried by holding down option key in system  display settings and there is no "Detect Dsiplays" ...
cheers

**Comment by 5T33Z0** [comment]
I don't have Thunderbolt in my machine.

**Comment by peaceofmind3241** [comment]
may bad. actually it is the MiniDisplayPort. can  connect to an external monitor through  MiniDisplayPort on win10 on the same box.

**Comment by 5T33Z0** [comment]
Works fine for me. Either use the second framebuffer patch or look for a T430 EFI. There are plenty of them out out there.

**Comment by peaceofmind3241** [comment]
thanks!
    On Friday, December 17, 2021, 04:47:50 PM EST, 5T33Z0 ***@***.***> wrote:  
 
 


Works fine for me. Either use the second framebuffer patch or look for a T430 EFI. There are plenty of them out out there.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
