### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Lenovo035** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#21]
Hello, your EFI also works for an X230, I did everything as described, but when you try to boot from the USB stick, the bar stops and nothing happens.

**Comment by Jan-E** [comment]
Did you activate  '#PciRoot(0x0)/Pci(0x2,0x0) 1366x768 px' without device_type in the device properties and disable the other one? See https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/issues/11 as well.

**Comment by 5T33Z0** [comment]
No Support for X230 from my end. It's a different model for a reason!
