### ISSUE TITLE
Dw1510 on Big Sur and up

### ISSUE THREAD

**Issue by juanpy0223** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#23]
Im using your clover efi On my x230t with some tweaking, Im running Catalina 10.5.3 with it, my wifi is DW 1510 bcm94322hm8l, I would like to know how to make it work on Big Sur and/or Monterey if I update or  clean install, can you please suggest how to do it.... 

Note: I use this wifi card, because I dual boot MacOs and Windows 

Thanks in advance!

**Comment by 5T33Z0** [comment]
All the required kexts for running Broadcom Cards on Big Sur and Monterey are present. DW1510 has been reported as incompatible: https://osxlatitude.com/forums/topic/11138-inventory-of-supportedunsupported-wireless-cards-2-sierra-monterey/
