### ISSUE TITLE
USB wake 

### ISSUE THREAD

**Issue by jozews321** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#24]
In your EFI you have the SSDT-Sleep_PRW-0D6D to fix the insta-wake issue. but doing this breaks waking from USB devices like a keyboard. Is there a way to enable waking from usb without the insta-wake issue?

**Comment by 5T33Z0** [comment]
Try ACPI. https://github.com/5T33Z0/OC-Little-Translated/issues/2

Have fun – you can send me the finished SSDT once your'e done.
