### ISSUE TITLE
Please help me 

### ISSUE THREAD

**Issue by Lenovo035** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#26]
Hello i have a problem i want to install the intel hd4000 patcher but it doesn't allow the installation because csrutil authenticated-root is set to enable but when i enter csrutil status in the terminal it shows me that everything is set to disable. When I try to disable Gatekeeper via hackingtool I get the error: mount failed with 66. Then I found a program that means bigsurmountrw because I can get into the system folder but the patcher still doesn't work because SIP is activated. I am already despairing.

**Comment by 5T33Z0** [comment]
Change csr-active-config to `EF0F0000` as instructed on the HD4000 Patcher Repo.

**Comment by Lenovo035** [comment]
I changed csr-active-config to EF0F0000. I even disabled csrutil again even in recovery mode in the terminal and type csrutil authenticated-root disable but still doesn't work

**Comment by 5T33Z0** [comment]
Enter  `sudo spctl --master-disable` in Terminal to disbale gatekeeper.
HD4000 patcheris only compatible wirh macOS Monterey , no Ventura support. Report any issues related to HD 4000 to the author of the patche.  The last time I used it it worked without issues.

**Comment by 5T33Z0** [comment]
No. NONE of this has doen in Recovery.

**Comment by Lenovo035** [comment]
Hello, sorry for contacting you again, I have a problem that Monterey only starts when the USB stick is plugged in. I have already copied the EFI folder from the USB stick and pasted it into the system EFI, but it does not start from the hard disk and shows in the BIOS He doesn't show me any more entries in the boot menu. Only when the USB stick is plugged in again can I change back in the bios from where to start. I do not know how to continue

**Comment by 5T33Z0** [comment]
1. I tested this EFI with macOS Monterey 12.5 again yesterday! It works!
2. Intel HD4000 Patcher = wroking!
3. Drives are detected in Bootpicker!
4. Installing macOS 12 on this machine is not recommended (as mentioned in the Readme)! Install macOS Catalina
5. Try some troubleshooting on your own!
6. Look for a different EFI!
