### ISSUE TITLE
Does this run with ME disabled? And is it possible to run this with coreboot and in dualbood with linux?

### ISSUE THREAD

**Issue by Zacki06** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#27]
Hello,

first of all, thanks for providing such an amazing guide on how to get a Hackintosh on this nice piece of hardware and for keeping it up to date :-)

My first question would be whether it is possible to run this install/the OS with Intel ME disabled. So far I have not read a lot about this and only comments of others but no concrete evidence. And since everyone only asks how to disable the ME with 1vyrain, I have no idea whether you can then re-enable it in case it doesn't work anymore but from what 1vyrain uses it might work.

My second question goes a bit deeper. I am planning on corebooting my T530 (and depending on the outcome of question one I'm also interested in removing/disabling the Intel ME).
Besides that, I'd like to dual-boot this machine, with macOS installed on the mSATA drive and Linux using the regular SATA.
I am fully aware that this is outside of the scope or your guide, but I was interested on your opinion on this topic.

**Comment by 5T33Z0** [comment]
Thanks for the props.

You can disable the Intel Management Engine in the BIOS but then the pre-booting stage (Lenovo Logo) stays a really long time before the actual bootmanger is loaded. My BIOS is jailbroken via IvyRa1n and I've readon the repo, that this behavior is expected when disabling it. Therefore I would advice against disabling Intel ME.  

I don't know what corebooting means and I have no experience with mSATA. I'm using a regular SATA SSD with 2 Partitions to dual-boot macOS and Windows.

**Comment by Zacki06** [comment]
Wow, I didn't expect an answer so fast :-)

I know that you used 1vyrain to unlock your BIOS, that's why I was asking. They provide an "easy" way to disable the Intel ME but I couldn't find anything about re-enabling it afterwards.
Disabling it brings certain "freedoms", so an increased boot-time is a tradeoff I'm worth accepting if it would still work.

As for [coreboot](https://www.coreboot.org/), this is a BIOS replacement with something that is opensource that also gives back some freedom over your hardware. This is obviously not required but as it is easily possible on this machine I'd like to do it.

Regarding the mSATA/SATA thing, on my X230 I'm booting Linux from that drive, even though it's officialy "not supported".
So I don't really worry about that too much. I'd prefer to keep macOS and Linux separate and I don't plan on running Windows on that machine, I'll just keep the SSD with the Win install that it came with as an emergency backup for a while.

**Comment by 5T33Z0** [comment]
I just tested it, since I couldn't remember:

- Disabling the ME requires the "Advanced" menu which you only get by using IvyRain or flashing a custom BIOS with a flasher. 
- You can re-enable ME through that menu as well, though
- POST takes longer (+5 seconds)
- Booting macOS takes significantly longer (+30 seconds at least). It just stalls for a while at  the end

**Comment by Zacki06** [comment]
Thanks for trying it out!
So that means it is possible, just not "convenient" to disable it.
Now I have to find out if that is also the case for installing it.

**Comment by 5T33Z0** [comment]
I guess so.
