### ISSUE TITLE
XHCI

### ISSUE THREAD

**Issue by Giinkie** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#28]
Hello, in BIOS on this point:
SATA > SATA Controller Mode: XHCI
I have only two choise:ACPI or Combined.
How to fix it? Install custom bios?

**Comment by 5T33Z0** [comment]
SATA > SATA Controller Mode: AHCI

**Comment by Giinkie** [comment]
> SATA > SATA Controller Mode: AHCI

Thanks!
