### ISSUE TITLE
VoodooSDHC possible replacement

### ISSUE THREAD

**Issue by dreamwhite** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#29]
Hi, what's your exact SD card reader PCI address? You can retrieve it from any PCI utility such as Hackintool, in PCIe section.

**Comment by 5T33Z0** [comment]
Hi. It's a Ricoh SD Card reader.

PciRoot(0x0)/Pci(0x1C,0x0)/Pci(0x0,0x0)

I think the kext is based on this one:

https://www.reddit.com/r/thinkpad/comments/5wbv0s/i_fixed_the_unusable_thinkpad_x230s_ricoh_sd_card/

**Comment by dreamwhite** [comment]
Oh alright, since it's a PCI reader, can you tell me `vendor-id` and `device-id`?

**Comment by 5T33Z0** [comment]
`vendor-id`: 0x1180
`device-id`: 0xE823

IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/EXP1@1C/IOPP/SLOT@0

**Comment by dreamwhite** [comment]
Ouch, seems like VoodooSDHC is the only known way to get the SD Card reader working. Closing this issue...
