### ISSUE TITLE
macOS Ventura

### ISSUE THREAD

**Issue by Lenovo035** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#30]
Hello, is there a chance to switch to macOS Ventura.
Best regards.

**Comment by 5T33Z0** [comment]
**NO!** See issue https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/issues/25

**Comment by 5T33Z0** [comment]
![Ventura_Proof](https://user-images.githubusercontent.com/76865553/207999617-ff1799ac-adf2-40d2-9306-a9eac3c19cd9.png)

Instructions later…
