### ISSUE TITLE
Keeps Rebooting

### ISSUE THREAD

**Issue by Themstr** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#33]
when i choose the install monterey from opencore bootloader it just panic and reboot after apple logo .

**Comment by 5T33Z0** [comment]
Install Monterey coming from which OS?

**Comment by Themstr** [comment]
i use mac os on vm i used legacy patcher to download mac os then i used the host linux to modify the efi folder

**Comment by 5T33Z0** [comment]
No support for VMs. Figure it out on your own. It's working fine when installed natively.
