### ISSUE TITLE
Install problems macOS Ventura

### ISSUE THREAD

**Issue by Lenovo035** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#34]
Hello 5T33Z, I have big problems installing macOS Ventura on my T430.
The previous EFI's worked idly what could it be I hope you can help me
because you are a professional in the field and have great respect for your work and effort to create EFI's and make us all very happy with it so that we can also enjoy macOS
many thanks
![Screenshot_20230112_134227_Gallery](https://user-images.githubusercontent.com/96473200/212072548-871e8c1c-915f-458b-a227-07f8a6f54991.png)
![Screenshot_20230112_134406_Gallery](https://user-images.githubusercontent.com/96473200/212072557-d8077389-ae19-4b19-ac94-d6768e2b5880.png)
![Screenshot_20230112_134455_Gallery](https://user-images.githubusercontent.com/96473200/212072562-72753dae-771e-4234-aeb7-a29cb006aa74.png)

**Comment by 5T33Z0** [comment]
Why do you expect support from me for a machine I don't even own and this EFI isn't even for?

Read and follow the deployment notes: - especially this part:  https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore#re-enabling-acpi-power-management-in-macos-ventura

Unless you have a custom BIOS with CFG Lock disabled you cannot use the EFI as is as. Add  the `ControlMsrE2.efi` to EFI/OC/Tools and run it from bootpicker, and check if it the MSR 0xE2 register locked or unlocked. If it is "locked" you have to disable the 2 kexts for AppleIntelCPUPowerManagement and force-enable XCPM instead to have decent CPU Power Management.

For pacthing your BIOS you can follow these instructions; https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/issues/31#issuecomment-1368409836

**Comment by Lenovo035** [comment]
I no longer get error messages, but I see the Apple logo, the screen is gray and absolutely nothing is happening do you have an idea.
![Uploading 20230112_153645.jpg…]()

**Comment by Lenovo035** [comment]
I no longer get error messages, but I see the Apple logo, the screen is gray and absolutely nothing is happening do you have an idea.
![20230112_153645](https://user-images.githubusercontent.com/96473200/212095446-7a2acdb9-a087-4f30-90b4-4112b321ab6e.jpg)

**Comment by 5T33Z0** [comment]
Did you run `ControlMsrE2.efi` as I asked you to? What was the result?

**Comment by Lenovo035** [comment]
This firmware has LOCKED MSR 0xE2 Register

**Comment by 5T33Z0** [comment]
Enable verbose mode (-v)

**Comment by Lenovo035** [comment]
I have one more question I've now managed to get into the installation program but when I try to install ventura I get the message that ventura is not compatible with the mac I've already tried no compat check but it doesn't work and on the other disk I have can install it with no problems and runs idly and when i copy the efi from the working hard drive over to the new one it texts me when trying macOS ventura is not compatible so i find that very odd

**Comment by 5T33Z0** [comment]
Read the inszall instructions. Especially the part about SMBIOS

https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/blob/main/macOS_Install/OpenCore/OC_macOS13.md

**Comment by sp4** [comment]
> This firmware has LOCKED MSR 0xE2 Register

You may have better luck using the 5T33Z0's previous release without the AppleIntel CPU power management. I'm up and running on that with minimal changes.

**Comment by Lenovo035** [comment]
An error occurred while preparing the software update. What is the procedure to get rid of this error?

**Comment by 5T33Z0** [comment]
NONE. And it's explained in the install instructions for macOS 13 right before the "Notes" section… and it's marked by a ⚠️ 

What more do you expect me to do?

So, since you have obviously managed to install macOS Ventura. I am closing this issue.
