### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Moretz** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#35]
Hello dear 5T33Z.
Firstly I would like to thank you for the EFI releases I have been using on my x230 for a year. MacOS from 10.14 to 12.4 started with minimal edits (screen resolution, ssdt-pm, gensmbios). But there is something wrong with the latest releases. I first discovered this by installing Ventura, the macOS installer wrote that my Mac was not supported. 
But later I discovered that now even the stable Big Sur refuses to install with the same error:
![photo_2023-01-16_13-45-47](https://user-images.githubusercontent.com/2368664/212660121-8ff81c57-3581-4a13-91ca-247c97dd1abb.jpg)

Can you tell me what might be the problem? Or open for download previous releases. Thanks.

**Comment by 5T33Z0** [comment]
Change SMBIOS to MacBookPro11,4 temporarily.

Read the install instructions for more details: https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/tree/main/macOS_Install

**Comment by Moretz** [comment]
A fresh Ventura installation required smbios from macbookPro14,2.
Thank you!

**Comment by 5T33Z0** [comment]
Oh you're right 14,1 is the minimum requirement for Ventura. I've got to adjust the guide. Anyway: once it's installed you can revert back to MacBookPro10,1 (i7) or MacBookPro10,2 (i5)
