### ISSUE TITLE
help needed: boot loop or stuck when boot from usb

### ISSUE THREAD

**Issue by lovitus** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#36]
* bios version is 2.77 official, already configured as the project describe
* SSDT-PM disabled as required (CPU is i7 3430QM if my memory was right)
* I've tried Ventura and Monterey, both failed at booting from installer
* Images ware written by Opencore legacy patcher 

Thanks for your guys' patient, I'm new to hackintosh.
My laptop is T530. If the boot log not clear enough,I could post the entire specifications later .
Thanks for your time if can help or just some information 

![20230225_174722](https://user-images.githubusercontent.com/14361541/221350960-3205c6ee-f770-488f-bd93-cdc7ce7942bc.jpg)

**Comment by 5T33Z0** [comment]
You need an unlocked BIOS to use the EFI as is. More info here: https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/CPU_Power_Management/CPU_Power_Management_(Legacy)#re-enabling-acpi-power-management-in-macos-ventura

**Comment by lovitus** [comment]
> You need an unlocked BIOS to use the EFI as is. More info here: https://github.com/5T33Z0/OC-Little-Translated/tree/main/01_Adding_missing_Devices_and_enabling_Features/CPU_Power_Management/CPU_Power_Management_(Legacy)#re-enabling-acpi-power-management-in-macos-ventura
> 
> So you either need to flash 1vyrain or use XCPM instead. And disable the `AppleIntelCPUPowerManagement` kexts

@5T33Z0 Hello , dear author , I saw your laptop runs "bios 2.77 ,unlocked " , mine is 2.77 also , should I downgrade the bios to 2.60 before trying to unlock it by 1vyrain.
thanks for your help

**Comment by 5T33Z0** [comment]
Follow the instructions on the [1vyrain](https://github.com/n4ru/1vyrain) github to downgrade and flash the modded BIOS or use XCPM instead. Don't ask me for instructions.
