### ISSUE TITLE
Add Sata hotplug 

### ISSUE THREAD

**Issue by jozews321** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#37]
Hey. I've been testing this patch for com.apple.driver.AppleAHCIPort that enables hotplug capabilities for the dvd drive bay I have connected and disconnected various hard drives and stuff and it's working fine.

The patch goes in Kernel/Patch

![Screenshot 2023-04-14 at 10 36 04 PM](https://user-images.githubusercontent.com/83997656/232183121-e3c46656-c53a-4433-bc6c-5a2c9de896d9.png)

**Comment by 5T33Z0** [comment]
Nice. Where did you get the HDD drive bay for the T530?

**Comment by jozews321** [comment]
You can get one by searching for a HDD caddy you have to get one that is 12.7mm so it fits in the t530

![copy-5390-12042017121716-1540-5390-190617100306](https://user-images.githubusercontent.com/83997656/232228536-9dc8d597-e03a-4f00-b18a-69e8bb3043bb.jpg)
It looks like this

**Comment by 5T33Z0** [comment]
Thanks, I add the patch to the config. But it will ne disabled by default, since I can't test it.

**Comment by bzliukai** [comment]
Hello, can you provide guidance on how to enable it in macOS catalina.
The latest EFI currently in use, with MacOS 10.15.7 boot prompt reading failed initialization, looks forward to your help 🙏

**Comment by 5T33Z0** [comment]
You need to change `MinKernel` to 19.0.0 and see if it works

**Comment by bzliukai** [comment]
Thank you.

**Comment by 5T33Z0** [comment]
Does it work? Because if it does, I change the patch descriotion to Catalina+
