### ISSUE TITLE
Ventura unsupported Mac 

### ISSUE THREAD

**Issue by KemuiHarumi** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#39]
Hello! ive been trying to get Ventura working on the Thinkpad T530. It already has Catalina installed but i would like to go to Ventura.

My specs are listed as : 

CPU : i5 3210M
GPU : Intel HD 4000
RAM : 4GB 
SSD : Netac S535N 128GB
Display : 1600x900

After doing the instructions shown in the guide. I always stop at this part. 
![IMG_0966](https://user-images.githubusercontent.com/111229915/234263283-29fe7be5-74b7-4fb4-a616-4a943c44befc.jpg)

I don't know if i have done anything wrong, and any help would be appreciated!

**Comment by 5T33Z0** [comment]
You nees to temporarily switch SMBIOS
https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/blob/main/macOS_Install/OpenCore/OC_macOS13.md

**Comment by KemuiHarumi** [comment]
Thanks! That worked well. im now at the process of installing MacOS.
