### ISSUE TITLE
Logitech HD Pro Webcam C920 not working in 3rd party Apps (Zoom, Microsoft Teams)

### ISSUE THREAD

**Issue by 5T33Z0** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#41]
So, I have this issue I don't know how to resolve: my C920 works fine in Photobooth and Facetime on my Lenovo T530. But when using any 3rd party apps like Zoom or Microsoft Teams, the cam won't turn on because I can't grant the apps access to it.  The cam is working fine on my desktop pc in Ventura which is even weirder:

![Bildschirmfoto 2023-04-30 um 11 53 40](https://user-images.githubusercontent.com/76865553/235346984-457c7394-a713-4f4f-9d09-466a8763e5b9.png)

Teams and Zoom both ask me to change the Security settings so access to the cam is granted (screenshot from Zoom):  

![Bildschirmfoto 2023-04-29 um 10 10 26](https://user-images.githubusercontent.com/76865553/235292276-0907208d-6fbc-4722-a6de-2b67dc1dfde7.png)

But on the Notebook, the apps don't show up in the Security/Privacy settings :

![Syssettings](https://user-images.githubusercontent.com/76865553/235291766-56d39d03-2c6d-49b0-b7e9-aebcb42d60dd.png)

I tried mapping USB ports which is not a necessity on this system but it had no effect. Changing SIP to EF0F0000 didn't have any effect either. I think the issue is related to this: https://superuser.com/questions/1441270/apps-dont-show-up-in-camera-and-microphone-privacy-settings-in-macbook

I'v tested it in Mojave, Big Sur, Monterey and Ventura – same result. Any suggestions on how to fix this would be highly appreciated.

**Comment by Jan-E** [comment]
I have got 2 apps listed under camera and microphone: Camera Recorder Lite and ond of my own iOS apps in a Catalyst version. Those permissions survived the upgrade from BIg Sur where the internal webcam is still functioning. The Camera Recorder Lite turns my internal webcam automatically on. But the internal webcam is not working any more in Monterey and Ventura (VDA decoder failed on my 1366*768 HD4000 screen). But the microphone still worked. Even the mike of a USB headphone that have never been connected before to this Ventura. So I could record a ‘video’ with only sound.
I could not get any microphone working for Skype (in Chrome), the Zoom app or the Teams app. All of them asked to give them permission in the System Settings but no new entries were there. So existing permissions (migrated from Monterey) are respected, but new ones aren’t added.

**Comment by 5T33Z0** [comment]
Okay, I found 2 solutions to fix the issue.

1. With SIP disabled (not a complete solution): 
- Reboot 
- In Bootpicker, hold Shift and Press Enter to boot macOS in Safe Mode… boot will take longer and graphics acceleration won't be available
- Run the App that needs access to the mic/cam
- The system will ask for permissions. Once you grant them, the App will be in the list of apps with access to the mic/cam
- Reboot normally.
- Voila

**Problem**: This worked fine for Zoom but Microsoft Teams won''t run in Safe Mode. There's no GUI and the promt for granting the app access to the mic/cam were not triggered. ;(

2. Enabling SIP: In order to be asked by the system to grant access to the camera and mic, SIP has to be enabled.  Once I re-enabled and rebooted , the prompts for grnating access were working immediately.

Problem: If you are using macOS 12+ you can't boot with SIP enabled.

**Comment by Jan-E** [comment]
There might be a third way: ask for permission for the Teams app in Big Sur and do the update to Ventura, maybe even in 2 steps. Something you really do not want to do.

**Comment by 5T33Z0** [comment]
This case is already covered in Option 1

**Comment by Jan-E** [comment]
It is now. But it was not in the 1st version of the comment (which I receuved by mail). In that version younonly had 2 options 👍
