### ISSUE TITLE
stuck on empty screen please help

### ISSUE THREAD

**Issue by UsetUset2244** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#42]
when i first boot it got to this not even showing options
![IMG_20230430_185825](https://user-images.githubusercontent.com/110706082/235363425-300aad44-ef48-46d8-855b-7d2729743997.jpg)

**Comment by 5T33Z0** [comment]
I just testest booting with the latest EFI folder from USB flash drive. Works fine.

**Comment by UsetUset2244** [comment]
yea i dont know why this is happening to me

**Comment by 5T33Z0** [comment]
Try disabling UEFI/Output/GopBurstMode and see if it changes anything

**Comment by jozews321** [comment]
@UsetUset2244 Also you should try to select the usb/ssd to boot first in BIOS and not use the F11 menu

**Comment by 5T33Z0** [comment]
Also: Make sure to check your USB Setings in BIOS (CONFIG Tab): 
- USB UEFI BIOS Support: Enabled
- USB 3.0 Mode: Enabled

**Comment by UsetUset2244** [comment]
it boots up now thanks
