### ISSUE TITLE
Booting is super slow with Mojave on X230

### ISSUE THREAD

**Issue by K4sum1** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#47]
I'm using this for my X230, because everything else I'm finding has some sort of bug that I can't find anything about online. This is the only OpenCore config I've found that can boot from the internal drive. Booting the installer (and the internal drive after its fully installed), the bar starts to very slowly crawl after around the 2/3rd mark, slowly filling until it finally boots. While it's in this state, there's no drive activity going by the light. The second boot (first from internal SSD) freezes with the bar only 1/25th filled or so, until after a few minutes or so jumping forward and beginning the second stage of the install. I checked NoTouchID, and it appears to be included in the release EFI, so I don't think it's that. Is there some other thing that I missed or isn't in the config? (I'm new to hackintoshing, I probably missed something obvious.) (Also I want Mojave for compatibility with older jailbreaking tools (existence of iTunes, x86 apps, etc) and newer jailbreaking tools. (most are minimum High Sierra))

**Comment by K4sum1** [comment]
Also not sure if related to X230 or some misconfiguration, but my trackpoint + trackpoint buttons don't work. I also replaced my WiFi card with an AW-CE123H, and macOS doesn't see it.

**Comment by 5T33Z0** [comment]
Did you read the Note? 

It explicitely states that this EFI is for the T530 ONLY and T430/X230 are not supported!

Mojave installation works flawlessly on my system — I just tested it.

If you want to make this config work on your system, you have to figure it out on your own, or look at other repos, like this one, for example: https://github.com/banhbaoxamlan/X230-Hackintosh

**Comment by K4sum1** [comment]
> If you want to make this config work on your system, you have to figure it out on your own, or look at other repos, like this one, for example: https://github.com/banhbaoxamlan/X230-Hackintosh

With that repo, OpenCore doesn't recognize macOS on my SSD. Do you know how I could fix that?

**Comment by K4sum1** [comment]
They're almost the same laptop, please just help me. I want to have this working please.

**Comment by K4sum1** [comment]
You fixed the WiFi issues with 0.9.7. Please it's so close to fully working. 🥺

**Comment by K4sum1** [comment]
So I taped pin 51 on the WiFi card when I didn't need to.

After removing the tape, AppleIntelCapriController still causes a busy timeout, but everything seems to work. The boot process is a lot faster now, if I keep VoodooSDHC disabled. If I reenable VoodooSDHC, I get the same timeout. Haven't tried with VoodooSDHC enabled, but trackpoint consistently works now.

**Comment by K4sum1** [comment]
So WiFi is broken now I guess. Will have to look into that now.

Also trackpoint seems to double click or more with a single click and it's not hardware. This would be so much easier if you just supported what is the same fucking laptop but smaller.

**Comment by K4sum1** [comment]
Copied EFI to internal drive, and now I'm stuck at End RandomSeed.
