### ISSUE TITLE
Slow on Ventura and Sonoma

### ISSUE THREAD

**Issue by tremebundo** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#49]
I have been able to install Ventura and Sonoma with this EFI, but the system is terribly slow. And I would like to know where to start checking for solutions.
Thanks.

**Comment by Jan-E** [comment]
Did you install the OCLP (OpenCore Legacy Patches)?

**Comment by tremebundo** [comment]
> Did you install the OCLP (OpenCore Legacy Patcher) root patches?

Yes.
Maybe it has to do something with the SSD access. I see a lot of activity.
My system has 16GB of RAM.

**Comment by Jan-E** [comment]
Maybe it is Spotlight, indexing the Mac. Try using the Activity Monitor to see what is happening.

**Comment by 5T33Z0** [comment]
Indexing takes up most of the CPU ressources when running macOS the first time. After that, the system should run as expected. If you have a diffferent CPU than an i7 3360, you need a different SSDT-PM file. I have a collection here: https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore/tree/main/ACPI/SSDT-PM

**Comment by tremebundo** [comment]
I left the computer on all last night and now seems to work more smoothly. I think the indexing task has ended, because I also see less hard disk activity.
I´ll try the SSDT-PM file in a few days.
Thanks a lot for your advice and forgive me for being so newbie.
