### ISSUE TITLE
Thinkpad T530 - 2429 model - Helper Docs

### ISSUE THREAD

**Issue by avoiceofreason** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#51]
This isn't an issue so much as some helpful hints for anyone with a fairly stock T530 and like me a Hackintosh newbie and struggling with getting MacOS (Sonoma) onto the laptop using this OC/EFI solution.

Firstly 5T33ZO has clearly done a lot of work on this build and has extensive documentation, so read that first.

BOOT-ARGS

First thing is add -v to boot-args. You need to know why the MacOS boot or install is failing. However don't expect too much help from the error messages or googling. it's a dark art and luck and guesswork seem to be the route to a successful MacOS install.

                    <key>boot-args</key>
                    <string>-v gfxrst=1 ipc_control_port_options=0 #-lilubetaall</string>

BIOS
The release build assumes you have a BIOS modded with 1vyrain. It says that in the pre-reqs.
However a stock BIOS (2.77 in my case) has MSR 0xE2 CPU register locked, and the kernel quirks are not enabled so MacOS will never boot successfully.

You have a choice. Mod BIOS with 1vyrain and enable CFG or add the 2 quirks:

                <key>AppleCpuPmCfgLock</key>
                <true/>
                <key>AppleXcpmCfgLock</key>
                <true/>

Optical Ultratray - DVD

I don't understand this one, and think I randomly stumbled upon a google search after looking up the usual incoherent MacOS error messages and kernel panics. But before Sonoma install you must eject the optical Ultrabay DVD drive or you'll never get through the install. After install you can put the drive back and it works fine, but during install it will just not allow the install to complete.

Screen Resolution

If you have 1366x768 SD resolution screen, make sure you follow the instructions to enable the correct Deviceproperties and disable the default HD device. You might even want to delete the HD section completely.

AUDIO

Can't imagine why you wouldn't want audio over DP, so go ahead and delete the No-hda-gfx from device PciRoot(0x0)/Pci(0x1B,0x0)
That worked for me anyway.

WIFI AND BLUETOOTH

I have a stock Centrino Advanced-N 6205 Wifi card in my T530. The default build here is for Broadcom devices so won't work for Intel Wifi cards. I used the itlwm drivers here: https://github.com/OpenIntelWireless/itlwm  You need to copy the kext to the /EFI/OC/Kexts folder and add the kernel section of the config.plist:

                <dict>
                    <key>Arch</key>
                    <string>Any</string>
                    <key>BundlePath</key>
                    <string>itlwm.kext</string>
                    <key>Comment</key>
                    <string>V2.3.0</string>
                    <key>Enabled</key>
                    <true/>
                    <key>ExecutablePath</key>
                    <string>Contents/MacOS/itlwm</string>
                    <key>MaxKernel</key>
                    <string></string>
                    <key>MinKernel</key>
                    <string></string>
                    <key>PlistPath</key>
                    <string>Contents/Info.plist</string>
                </dict>

Note that you also need to install the HeliPort app in MacOS to configure WiFi. It doesn't use the normal WiFi applet: https://openintelwireless.github.io/HeliPort/

However you can edit the Info.plist inside the itlwm.kext and hard code the SSID and password which means WiFi will work and connect at install/boot etc.

Make sure you remove all the Broadcom Wifi kexts from config.plist. They usually start with Brcm

On Bluetooth, you need the drivers here: https://openintelwireless.github.io/IntelBluetoothFirmware/

As per the docs:

Install IntelBTPatcher.kext (Depends on Lilu v1.6.2 or newer)
Make sure IntelBluetoothFirmware.kext v2.2.0 or newer is used.
Remove/Exclude IntelBluetoothInjector.kext for macOS Monterey and newer from the Bootloader's config
Install BlueToolFixup.kext

Note that for me IntelBluetoothFirmware.kext caused Sonoma to bootloop and panic. So do not load this kext

I never got Bluetooth working. I'm not sure if I have a hardware issue, or maybe some USB mapping issue or just that bluetooth on this laptop is not supported. 

POST INSTALL STUFF

Follow ST33ZO's guide for post install. Certainly instal the most recent OpenCore Patcher GUI app and apply all the root kernel patches to make the accelerated graphics work etc.

Apple ID, iMessages, Facetime

I followed the dortania guide here: https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios

I used Gensmbios to generate and inject the correct Platform NVRAM ID's into the config.plist.

Can log into my Apple ID, but not managed to get iMessage or Facetime working, just keeps asking to authenticate (????)

Not sure if its something to do with EN0 being the ethernet port and EN1 being wireless. I did add the Intel Wifi card into the config.plist and added "built-in" but didn't work:

                <key>PciRoot(0x0)/Pci(0x1C,0x1)/Pci(0x0,0x0)</key>
                <dict>
                    <key>AAPL,slot-name</key>
                    <string>Internal@0,28,1/0,0</string>
                    <key>built-in</key>
                    <data>AQ==</data>
                    <key>device_type</key>
                    <string>Network controller</string>
                    <key>model</key>
                    <string>Centrino Advanced-N 6205 [Taylor Peak]</string>
                </dict>

ROM is generated from gensmbios and doesn't match the hardware EN0 or EN1. issue??

Thats about it. I've included my working config.plist. It's possible I made other changes I forgot about.

Finally thanks to ST33Z0. Above is no criticism, just to help idiots like me.

[config.plist.zip](https://github.com/user-attachments/files/16818472/config.plist.zip)

**Comment by 5T33Z0** [comment]
I appreciate your suggestions and the effort to put into them. But it seems that you did not read the `Deployment` section, especiylly the part about ["Preparing the config.plist"](https://github.com/5T33Z0/Lenovo-T530-Hackintosh-OpenCore?tab=readme-ov-file#deployment), which overs most of the  things you mention already.

For the rest:

1. Boot-args: I assume that users are capable of adding `-v` themselves, if they need it…  **BTW**: Entering `CMD` and `v` in boot-menu will boot macOS in verbose mode. 
2. Kernel quirks for booting with unmodified BIOSes: already covered in the "Preparing the config.plist" section
3. Optical Drive bay: I never had to detach it to install any macOS, not even Sonoma. My DVD drive works fine and it never caused any issues when installing macOS, so I won't suggest that.
4. Screen Resolusion for different display panels: also covered already under "Preparing the config.plist"…
5. Audio: Covered in "Preparing the config.plist" section as well.
6. Wifi and Bluetooth: Covered in  "Preparing the config.plist" section as well. I won't include settings for YOUR Wi-Fi card in my repo/config.
7. Generating SMBIOS Data: I assume user know how to do this. But I may consider linking to GenSMBIOS.

Have a nice weekend.

**Comment by avoiceofreason** [comment]
Yep, I did read all the docs, very carefully, but we are not all hackintosh experts, and the starting point for many will be a vanilla T530. My notes are just pointers for first timers that might save them a few hours and 100+ boot attempts.

The DVD one was odd, but 100% repeatable on my 2429 model.

Cheers
