### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by my05** [5T33Z0/Lenovo-T530-Hackintosh-OpenCore#52]
but rather a huge thank you for providing this great instruction (and artefacts) that rather easily could enable me to finally run Sonoma on the T530 sibling, the W530 :)

I learned a lot from the files provided here and could also enable BT mouse support, etc (something i could not yet do on my Fujitsu 729U for example, that uses the same wifi/BT card as the W530...).

Still trying to figure out if it is possible to enable the SD slot (and even pciexpress slot), but that will be a mere bonus if that would be possible.

So great kudos for this, it was truly helpful and great :) Thank you.

**Comment by 5T33Z0** [comment]
Thanks for the feedback. SD Card used to work in previous versions of macOS (Big Sur, Monterey, I think). Since I have 2 newer laptops. I haven't tested SD Card in a while I didn't check.

I don't have any PCIe cards so I cannot test it. 

I guess you have to do some research on your own. Using Device Manager in Windows is a good starting place to get the device ID of the slot and go from there. In macOS you need IORegistryExplorer to check if the device is detected.

**Comment by my05** [comment]
Thank YOU 5T33Z0 for doing all the heavy work :)

This evening i could successfully install Sequioa on this machine

![IMG_20241113_192715](https://github.com/user-attachments/assets/1cfffa35-593d-41c4-9a37-99351c0b391c)

With working wifi (itwlm) and bluetooth (acidanthera kexts) and of course OCLP for the HD4000 igpu.

I will investigate the card-reader and expresscard 34 (if at all possible).

**Comment by my05** [comment]
Addition. The Ricoh SD-slot actually works after installing this package even under Sequioa:

https://github.com/chris1111/JMicron-Card-Reader

with no issues yet. Next up, the Expresscard slot...

**Comment by 5T33Z0** [comment]
This doesn't work for me. This package is for Card Readers from JMicron and not RIcoh. Maybe the W530 uses a drifferent ready than the T530.

**Comment by my05** [comment]
I believe it does differ there unfortunately. I double checked and the W530 uses this guy:

SCSI\DiskRicoh_Storage_SD&REV_3.0

So they differ a bit (which was surprising to me imho). No bit deals imho :). You did the absolute lion part of the work with the T530 and i'm just hanging around for the ride. This SD issue will get solved with some time.

Again - Thank you for the stellar work on the foundation :)
